Updated README.md
whimc/Science-Tools pull request #15
Opened 2021-04-09 18:00 UTC by EmiCB

- updated plugin description
- added config guide
- added list of commands

2021-04-14 21:23 UTC, jackah2 requested changes

2021-04-14 21:23 UTC, jackah2 commented on README.md
> +The config file can be found under /plugins/WHIMC-ScienceTools/config.yml. Use `/sciencetools reload` whenever you change the config.
```suggestion
The config file can be found under `/plugins/WHIMC-ScienceTools/config.yml`. Use `/sciencetools reload` whenever you change the config.
```

2021-04-14 21:23 UTC, jackah2 commented on README.md
> +Unit conversions config will look like this:
```suggestion
### Unit Conversions
Unit conversions config will look like this:
```
While the general structure of the config is nice to have, having a real example would be nice too. For example,

```yaml
conversions:
  fahrenheit: # Celcius -> Fahrenheit
    expression: '({VAL} * 9.0 / 5.0) + 32.0'
    unit: °F
  feet: # Meters -> Feet
    expression: '{VAL} * 3.28084'
    unit: ft
```

Along these lines, I'd like to have a table including the placeholders that are possible and what they mean:

|Placeholder|Description|
|-|-|
|`{VAL}`|The value that is being converted|

2021-04-14 21:23 UTC, jackah2 commented on README.md
> +```
```suggestion
```yaml
```
You can provide a language for code blocks. Making them `yaml` code blocks gives syntax highlighting. You should do this in the other config blocks too.

2021-04-14 21:23 UTC, jackah2 commented on README.md
> +Science tool config will look like this:
```suggestion
### Science Tools
Science tool config will look like this:
```

2021-04-14 21:23 UTC, jackah2 commented on README.md
> +```
Similar to before, a real-world example and a table of possible placeholders would be nice to add.

2021-04-14 21:23 UTC, jackah2 commented on README.md
> +| /sciencetools js          | Run interpreted JavaScript    |
```suggestion
| `/sciencetools`           | Display command help          |
| `/sciencetools validate`  | Have a user validate a tool   |
| `/sciencetools reload`    | Reload the plugin's config    |
| `/sciencetools js`        | Run interpreted JavaScript    |
```

2021-04-14 21:23 UTC, jackah2 commented on README.md
> +| /sciencetools validate    | Have a user validate a tool   |
I think this command can have its own section. There are two ways that you can use it:
1. `/sciencetools validate <tool> <player>`. This will take the value of the tool at the target player's current location
2. `/sciencetools validate <tool> <player> <world> <x> <y> <z>`. Instead of taking the value of the tool at the target player's location, the provided location is used instead.

Also providing examples for these commands will be nice.

2021-04-14 21:23 UTC, jackah2 commented on README.md
> +---
No section the `validation` part within the config?

2021-05-24 17:24 UTC, Geph approved these changes
Looks good to me!

2021-05-24 19:47 UTC, jackah2 requested changes

2021-05-24 19:47 UTC, jackah2 commented on README.md
> +|`{Y}`          | The player's Y position           |
There are a handful of other placeholders including some functions that should be bete. The rest looks good :)

2021-05-24 21:45 UTC, jackah2 approved these changes
Looks good!

2021-05-24 23:00 UTC, merged