Making messages configurable
whimc/Science-Tools pull request #44
Opened 2021-09-05 19:41 UTC by samhum

Wrote local and global messages for science tool measurements and if tools are disabled on world. Prioritizes local before global if defined in both.

2021-09-06 05:12 UTC, jackah2 requested changes

2021-09-06 05:12 UTC, jackah2 commented on src/main/java/edu/whimc/sciencetools/models/sciencetool/ScienceToolManager.java
> +            }
```suggestion
            String message = globalMessageSection.getString(messageKey);
            Utils.log("&b\t- &f" + messageKey + "&b: \"&f" + message + "&b\"");
            globalMessages.put(messageKey, new Message(message));
        }
```

2021-09-06 23:58 UTC, samhum commented on src/main/java/edu/whimc/sciencetools/models/sciencetool/Message.java
> +    Message(String m)
I think I fixed most of the styling let me know if you find other stuff.

2021-09-07 00:00 UTC, samhum commented on src/main/java/edu/whimc/sciencetools/models/sciencetool/Message.java
> +            msg = msg.replace(UNIT_PLACEHOLDER,unit);
Yeah I was being lazy and was using the method also for disabled worlds to handle null arguments. I added a toString to replace the redundant checks for disabled worlds.

2021-09-07 00:02 UTC, samhum commented on src/main/java/edu/whimc/sciencetools/models/sciencetool/ScienceTool.java
> +                       Map<String,Message>globalMessages,
I stored it in ScienceToolManager and created a static getter to access the global messages since one set of global messages are shared between the tools.

2021-09-07 00:02 UTC, samhum commented on src/main/java/edu/whimc/sciencetools/models/sciencetool/ScienceToolManager.java
> +
I was trying to separate tools from global stuff, but no real reason. I moved it back.

2021-09-07 13:09 UTC, jackah2 requested changes
Main change here is shifting to an Enum model to maintain messages instead. a couple formatting nitpicks too

2021-09-07 13:09 UTC, jackah2 commented on src/main/java/edu/whimc/sciencetools/models/sciencetool/ScienceTool.java
> +    protected Map<String, Message> messages;
Gah, with the messages Enum, this won't even need to be stored anymore.

2021-09-07 13:09 UTC, jackah2 commented on src/main/java/edu/whimc/sciencetools/models/sciencetool/ScienceToolManager.java
> +    private static Map<String, Message> globalMessages;
I commented this before writing the Enum comment. I don't think `ScienceTollsManager` would even need any changes with the new approach.

2021-09-07 13:09 UTC, jackah2 commented on src/main/java/edu/whimc/sciencetools/models/sciencetool/ScienceTool.java
> +    protected Map<String, Message> messages;
Also, don't forget to use the custom formatting for plain `ScienceTool`s!

2021-09-07 13:09 UTC, jackah2 commented on src/main/java/edu/whimc/sciencetools/models/sciencetool/NumericScienceTool.java
> +            message+=" ("+converted+conversion.getUnit()+")";
```suggestion
            message += " (" + converted + conversion.getUnit() + ")";
```
Formatting nitpick again sorry

2021-09-13 12:46 UTC, samhum commented on src/main/java/edu/whimc/sciencetools/models/sciencetool/ScienceTool.java
> +    protected Map<String, Message> messages;
Think I removed all of the attributes and constructors referencing storing messages. Also thx totally forgot about plain ScienceTools I changed the class to use Messages too.

2021-09-13 12:47 UTC, samhum commented on src/main/java/edu/whimc/sciencetools/models/sciencetool/Message.java
> +package edu.whimc.sciencetools.models.sciencetool;
Let me know what you think I changed messages to use a similar format. It has the same functionality but I agree probably a better design.

2021-09-13 22:31 UTC, jackah2 requested changes

2021-09-13 22:31 UTC, jackah2 commented on src/main/java/edu/whimc/sciencetools/models/sciencetool/Message.java
> +        String fallback = (String) config.get("messages." + this.configPath);
You can just use the `getString` method instead of `get` so you don't have to cast to a String. Same thing for a couple lines down

2021-09-13 22:31 UTC, jackah2 commented on src/main/java/edu/whimc/sciencetools/models/sciencetool/Message.java
> +        if(local != null)
Really just a styling thing but I'd like to stick with explicit brackets on if/else statements. I'm also a fan of putting the else statement on the same line as the previous closing bracket.
```java
if (true) {
  something();
} else {
  somethingElse();
}

2021-09-13 22:31 UTC, jackah2 commented on src/main/java/edu/whimc/sciencetools/models/sciencetool/Message.java
> +        if(tool instanceof NumericScienceTool) {
I'm still seeing a few spacing things, mostly after if statement and parameters in methods
`if (...)` instead of `if(...)` and `foo(bar, baz)` instead of `foo(bar,baz)`.

2021-09-13 22:31 UTC, jackah2 commented on src/main/resources/config.yml
> +      #numeric-measure-format: '{MEASUREMENT}'
I'd keep commented lines out of the config. Instead, add stuff to the readme.

2021-09-13 22:32 UTC, jackah2 commented
Overall looking pretty good. Just some styling changes at this point.

2021-09-17 12:11 UTC, jackah2 approved these changes
Looks good! Thank you for doing this :)

2021-09-17 12:14 UTC, jackah2 requested changes
Oh wait one small thing actually. Could you update the README to include the new options with descriptions and examples

2021-09-20 23:07 UTC, jackah2 commented on README.md
> +
Can you add an example for tool-specific messages too

2021-09-20 23:15 UTC, jackah2 approved these changes
Awesome, looks good! Feel free to merge the PR :)

2021-09-21 01:34 UTC, merged