fixed data null issue
whimc/Science-Tools pull request #54
Opened 2021-11-20 19:28 UTC by GurmanToor

Will eliminate NPE issues with data variable

2021-11-29 00:10 UTC, jackah2 requested changes
Thanks for working on this! Minor change noted. Also could you bump the patch version in the `pom.xml`

2021-11-29 00:10 UTC, jackah2 commented on src/main/java/edu/whimc/sciencetools/models/sciencetool/QuestsScienceToolObjective.java
> +            if (data != null) {
I'd prefer a guard clause to avoid an additional level of indentation
```java
if (data == null) {
    continue;
}
// rest of the code stays the same
```

2021-11-29 18:03 UTC, Geph commented on src/main/java/edu/whimc/sciencetools/models/sciencetool/QuestsScienceToolObjective.java
> +            if (data != null) {
I'm assuming this will get rid of the console spamming exceptions like we've been seeing - Jack I'm too old/dumb to know what a "guard clause" is but I can bump the version number if that'll help move things along?

2021-11-30 00:57 UTC, jackah2 commented on src/main/java/edu/whimc/sciencetools/models/sciencetool/QuestsScienceToolObjective.java
> +            if (data != null) {
> 

Yes thank you :)

2021-12-13 18:14 UTC, jackah2 approved these changes

2021-12-13 18:14 UTC, jackah2 commented
Resolves #53

2021-12-13 18:14 UTC, merged